driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true


verifier:
  name: inspec

platforms:
  - name: centos-6.8
  - name: centos-7.3
  - name: debian-7.11
  - name: debian-8.6
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
- name: default
  run_list:
  - recipe[test::single_node]
  attributes:
    graphite:
      listen_port: "8080"
      uwsgi:
        workers: 4
        listen_http: true
