---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: ubuntu-10.04
  run_list:
  - recipe[apt]
- name: centos-6.4
  run_list:
  - recipe[yum]
- name: centos-5.9
  run_list:
  - recipe[yum]

suites:
- name: default
  run_list:
  - recipe[graphite]
  attributes: {}

- name: ssl
  run_list:
  - recipe[graphite_test::ssl]
  - recipe[graphite]
  attributes: {
    "graphite": {
      "ssl": {
        "enabled": true,
        "ca_certificate_file":  "/etc/ssl/server.crt"
      },
      "listen_port": "443"
    }
  }

- name: uwsgi
  run_list:
  - recipe[graphite]
  attributes: {
    "graphite": {
      "listen_port": "8080",
      "web_server": "uwsgi"
    }
  }

- name: carbon-relay
  run_list:
  - recipe[graphite]
  - recipe[graphite::carbon_relay]
  attributes: {
    "graphite": {
      "carbon": {
        "relay": {
          "destinations": [ "127.0.0.1:2003:a" ]
        },
      },
      "relay_rules": [
        {
          "name": "example_pattern",
          "pattern": "^mydata\\.foo\\..+",
          "destinations": [ "10.1.2.3:2004" ]
        },{
          "name": "example_default",
          "default": true,
          "destinations": [ "127.0.0.1:2004" ]
        }
      ]
    }
  }
- name: carbon-aggregator
  run_list:
  - recipe[graphite]
  - recipe[graphite::carbon_aggregator]
  attributes: {
   "graphite": {
      "storage_aggregation": [
        {
          "name": "all_min",
          "pattern": ".min$",
          "xFilesFactor": "0.1",
          "aggregationMethod": "min"
        }
      ],
      "aggregation_rules": [
        {
          "output_template": "<env>.applications.<app>.all.requests",
          "frequency": "60",
          "method": "sum",
          "input_pattern": "<env>.applications.<app>.*.requests"
        },{
          "output_template": "<env>.applications.<app>.all.latency",
          "frequency": "60",
          "method": "sum",
          "input_pattern": "<env>.applications.<app>.*.latency"
        }
      ]
    }
  }
- name: federated
  run_list:
  - recipe[graphite::federated]
  attributes: {}
- name: carbon-instances
  run_list:
  - recipe[graphite]
  - recipe[graphite::carbon_relay]
  attributes: {
    "graphite": {
      "carbon": {
        "instances": [
          {
            "instance_name": "test1-a",
            "options": {
              "LINE_RECEIVER_PORT": 2013,
              "UDP_RECEIVER_PORT": 2013,
              "PICKLE_RECEIVER_PORT": 2014,
              "CACHE_QUERY_PORT": 7012
            }
          }, {
            "instance_name": "test1-b",
            "options": {
              "LINE_RECEIVER_PORT": 2023,
              "UDP_RECEIVER_PORT": 2023,
              "PICKLE_RECEIVER_PORT": 2024,
              "CACHE_QUERY_PORT": 7022
            }
          }
        ],
        "relay": {
          "line_receiver_port": 3003,
          "udp_receiver_port": 3003,
          "pickle_receiver_port": 3004,
          "method": "consistent-hashing",
          "destinations": ["localhost:2013:test1-a", "localhost:2023:test1-b"],
          "instances": [
            {
              "instance_name": "test1-a",
              "options": {
                "LINE_RECEIVER_PORT": 3013,
                "UDP_RECEIVER_PORT": 3013,
                "PICKLE_RECEIVER_PORT": 3014,
              }
            },
            {
              "instance_name": "test1-b",
              "options": {
                "LINE_RECEIVER_PORT": 3023,
                "UDP_RECEIVER_PORT": 3023,
                "PICKLE_RECEIVER_PORT": 3024,
              }
            }
          ]
        }
      }
    }
  }
