---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-12.04
  run_list:
    - recipe[ubuntu]
- name: centos-6.4
  run_list:
    - recipe[yum-epel]
    
suites:
- name: single-node
  run_list:
  - recipe[runit]
  - recipe[graphite_example::single_node]
  attributes:
    graphite:
      listen_port: "8080"
      uwsgi:
        workers: 4
        listen_http: true
- name: carbon-aggregator
  run_list:
  - recipe[runit]
  - recipe[graphite_example::carbon_aggregator]
- name: carbon-cache
  run_list:
  - recipe[runit]
  - recipe[graphite_example::carbon_cache]
- name: carbon-relay
  run_list:
  - recipe[runit]
  - recipe[graphite_example::carbon_relay]
