Lint/ParenthesesAsGroupedExpression:
  Exclude:
    - 'test/**/*'

Style/GuardClause:
  Exclude:
    - 'libraries/provider_carbon_conf_accumulator.rb'
    - 'spec/spec_helper.rb'
    - 'spec/support/example_groups/provider_example_group.rb'
