sudo: required

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  matrix:
  - INSTANCE=default-centos-7
  - INSTANCE=default-centos-7 CHEF_VERSION=13
  - INSTANCE=default-debian-8
  - INSTANCE=default-debian-8 CHEF_VERSION=13
  - INSTANCE=default-debian-9
  - INSTANCE=default-debian-9 CHEF_VERSION=13
  - INSTANCE=default-ubuntu-1604
  - INSTANCE=default-ubuntu-1604 CHEF_VERSION=13

# Ensure we make ChefDK's Ruby the default
before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/cookstyle --version
  - /opt/chefdk/embedded/bin/foodcritic --version

script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}

matrix:
  allow_failures:
    - env: INSTANCE=default-centos-7
    - env: INSTANCE=default-debian-8
    - env: INSTANCE=default-debian-9
    - env: INSTANCE=default-ubuntu-1604
  include:
    - script:
      - /opt/chefdk/bin/chef exec delivery local all
      env: UNIT_AND_LINT=1
